version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "4200:4200"
    volumes:
      - ./project:/project
    command: >
      sh -c "ng serve --host 0.0.0.0 --port 4200"
